services:
  - type: web
    name: django-backend
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_react.settings_docker
      - key: API_HOST
        value: django-backend-xfkt.onrender.com
      - key: APP_HOST
        value: https://spleeter-web.onrender.com
      - key: PORT
        value: 8000
      - key: CELERY_BROKER_URL
        value: rediss://red-cu7i9jbv2p9s73bggou0:WGntlRAF8zil01wh8UsxlAb5hFeuDAou@oregon-redis.render.com:6379
      - key: CELERY_RESULT_BACKEND
        value: rediss://red-cu7i9jbv2p9s73bggou0:WGntlRAF8zil01wh8UsxlAb5hFeuDAou@oregon-redis.render.com:6379
      - key: ALLOWED_HOSTS
        value: django-backend-xfkt.onrender.com,spleeter-web.onrender.com
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: postgres://user:password@db:5432/mydatabase

  - type: worker
    name: celery-worker
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_react.settings_docker
      - key: CELERY_BROKER_URL
        value: rediss://red-cu7i9jbv2p9s73bggou0:WGntlRAF8zil01wh8UsxlAb5hFeuDAou@oregon-redis.render.com:6379
      - key: CELERY_RESULT_BACKEND
        value: rediss://red-cu7i9jbv2p9s73bggou0:WGntlRAF8zil01wh8UsxlAb5hFeuDAou@oregon-redis.render.com:6379

  - type: redis
    name: celery-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
