services:
  - type: web
    name: django-backend
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_react.settings_docker
      - key: API_HOST
        value: https://django-backend-xfkt.onrender.com
      - key: APP_HOST
        value: https://spleeter-web.onrender.com
      - key: PORT
        value: 8000
      - key: CELERY_BROKER_URL
        value: redis://celery-redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://celery-redis:6379/0
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: postgres://user:password@db:5432/mydatabase

  - type: worker
    name: celery-worker
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_react.settings_docker
      - key: CELERY_BROKER_URL
        value: redis://celery-redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://celery-redis:6379/0

  - type: redis
    name: celery-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
